dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - binutils_impl_linux-64=2.40
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - cairomm-1.16=1.16.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.37
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - cycler=0.12.1
  - dbus=1.13.6
  - epoxy=1.5.10
  - expat=2.6.2
  - ffmpeg=4.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc=13.2.0
  - gcc_impl_linux-64=13.2.0
  - gdk-pixbuf=2.42.12
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - graph-tool=2.67
  - graph-tool-base=2.67
  - graphite2=1.3.13
  - gtk3=3.24.42
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hicolor-icon-theme=0.17
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.0.15
  - libcups=2.3.3
  - libcurand=10.3.7.37
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgirepository=1.80.1
  - libglib=2.80.2
  - libgomp=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - librsvg=2.58.0
  - libsanitizer=13.2.0
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libtorch=2.3.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - matplotlib-base=3.9.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - nomkl=1.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - pango=1.52.2
  - pcre2=10.43
  - pip=24.2
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pycairo=1.26.0
  - pycparser=2.22
  - pygobject=3.48.2
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.3
  - sigcpp-3.0=3.6.0
  - six=1.16.0
  - sleef=3.6.1
  - sparsehash=2.0.3
  - sqlite=3.41.2
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - typing_extensions=4.12.2
  - wayland=1.22.0
  - xkeyboard-config=2.41
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.3
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - accelerate==0.33.0
      - addict==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - alembic==1.13.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - apscheduler==3.10.4
      - asttokens==2.4.1
      - attrs==23.2.0
      - autopage==0.5.2
      - babel==2.15.0
      - backcall==0.2.0
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.43.3
      - bleach==6.1.0
      - bs4==0.0.1
      - certifi==2023.11.17
      - cfgv==3.4.0
      - clarabel==0.9.0
      - click==8.1.7
      - cliff==4.7.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - commonmark==0.9.1
      - contexttimer==0.3.3
      - contourpy==1.2.0
      - cryptography==43.0.0
      - cvxpy==1.5.3
      - cython==3.0.7
      - datasets==2.20.0
      - dateparser==1.2.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dgl==2.3.0+cu121
      - diffusers==0.29.0
      - dill==0.3.8
      - distlib==0.3.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docutils==0.21.2
      - easydict==1.11
      - ecos==2.0.14
      - einops==0.8.0
      - elastic-transport==8.13.0
      - elasticsearch==7.9.1
      - emoji==2.12.1
      - executing==2.0.1
      - fabric==3.2.2
      - fastapi==0.112.0
      - fastjsonschema==2.19.1
      - fcd-torch==1.0.7
      - filelock==3.13.1
      - fire==0.6.0
      - flake8==7.0.0
      - flash-attn==2.6.3
      - fonttools==4.46.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - future==1.0.0
      - galore-torch==1.0
      - gensim==4.3.3
      - gitdb==4.0.11
      - gitignore-parser==0.1.11
      - gitpython==3.1.40
      - google==3.0.0
      - gpytorch==1.12
      - grakel==0.1.10
      - grave==0.0.3
      - greenlet==3.0.3
      - h11==0.14.0
      - happybase==1.2.0
      - hnswlib==0.8.0
      - huggingface-hub==0.24.5
      - hydra-core==1.3.2
      - identify==2.5.36
      - idna==3.4
      - imageio==2.33.1
      - imagesize==1.4.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.4
      - install==1.3.5
      - invoke==2.2.0
      - ipython==8.12.3
      - itchat==1.3.10
      - jaxtyping==0.2.31
      - jedi==0.19.1
      - jieba==0.42.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonpickle==3.2.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - lazy-loader==0.3
      - lightning-utilities==0.11.2
      - linear-operator==0.5.2
      - littleutils==0.2.2
      - llvmlite==0.41.1
      - lxml==5.2.2
      - mako==1.3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.6
      - mc-bin-client==1.0.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmengine==0.10.4
      - msgpack==1.0.8
      - much==0.0.7
      - multidict==6.0.5
      - multiprocess==0.70.16
      - munch==4.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - numba==0.58.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - ogb==1.3.6
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - optuna==2.4.0
      - osqp==0.6.7.post1
      - outdated==0.2.2
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.1
      - paramiko==3.4.0
      - parso==0.8.3
      - pbr==6.0.0
      - peft==0.12.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pipreqs==0.5.0
      - platformdirs==4.2.1
      - plotly==5.18.0
      - plumbum==1.8.3
      - ply==3.11
      - pre-commit==3.7.1
      - prettytable==3.10.0
      - prompt-toolkit==1.0.14
      - protobuf==4.25.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycodestyle==2.11.1
      - pycrawlers==1.1.6
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyemd==1.0.0
      - pyflakes==3.2.0
      - pyg-lib==0.4.0+pt23cu121
      - pygments==2.17.2
      - pygsp==0.5.1
      - pyinquirer==1.0.3
      - pymongo==4.8.0
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pyperclip==1.8.2
      - pypng==0.20220715.0
      - pyproject-toml==0.0.10
      - pyqrcode==1.2.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.2.5
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qdldl==0.1.7.post4
      - qqbot==2.3.11
      - ray==2.34.0
      - rdkit==2023.9.6
      - recommonmark==0.7.1
      - referencing==0.35.1
      - regex==2023.10.3
      - rich==13.7.1
      - rpds-py==0.18.0
      - rpyc==6.0.0
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - sacred==0.8.5
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scs==3.2.6
      - seml==0.5.1
      - sentencepiece==0.2.0
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - setuptools==73.0.1
      - shellingham==1.5.4
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.30
      - stack-data==0.6.3
      - starlette==0.37.2
      - stevedore==5.2.0
      - sympy==1.12
      - tabulate==0.9.0
      - tap==0.2
      - tenacity==8.2.3
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - thriftpy2==0.4.20
      - tifffile==2023.12.9
      - timm==1.0.8
      - tinycss2==1.3.0
      - tinydb==4.8.0
      - tinydb-serialization==2.1.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.3.0+cu121
      - torch-cluster==1.6.3+pt23cu121
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - torchaudio==2.3.0+cu121
      - torchdata==0.8.0
      - torchmetrics==1.4.0.post0
      - torchtyping==0.1.5
      - torchvision==0.18.0+cu121
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.0
      - transformers==4.28.0
      - triton==2.3.0
      - typeguard==2.13.3
      - typer==0.12.4
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - tzlocal==5.2
      - urllib3==2.1.0
      - uvicorn==0.29.0
      - virtualenv==20.26.2
      - wandb==0.16.0
      - wcwidth==0.2.12
      - webencodings==0.5.1
      - wheel==0.43.0
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.19.0
